---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/skabashnyuk/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-service-provider-integration-operator
