apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - https://github.com/konflux-ci/remote-secret/config/overlays/openshift_vault?ref=9f413da1d4703640b50fb03094f4b39e579c4bdb

namespace: remotesecret

images:
  - name:  quay.io/redhat-appstudio/remote-secret-controller
    newName: quay.io/redhat-appstudio/remote-secret-controller
    newTag: 9f413da1d4703640b50fb03094f4b39e579c4bdb

patches:
  - target:
      kind: ConfigMap
      name: remote-secret-controller-manager-environment-config
    path: config-patch.json
