apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - https://github.com/redhat-appstudio/remote-secret/config/overlays/openshift_vault?ref=2293738d33a4ffccbd83ade59d9b32cfc8e5b713

namespace: remotesecret

images:
  - name:  quay.io/redhat-appstudio/remote-secret-controller
    newName: quay.io/skabashn/remote-secret-controller
    newTag: main_2023_11_16__18_53_39

patches:
  - target:
      kind: ConfigMap
      name: remote-secret-controller-manager-environment-config
    path: config-patch.json
