apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/redhat-appstudio/build-service/config/default?ref=c214c7ecad9e2b65834089c123d89d8157ad078c
namespace: build-service
images:
  - name: quay.io/redhat-appstudio/build-service
    newName: quay.io/skabashn/build-service
    newTag: STONEBLD-2380_2024_05_02__15_05_13
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: controller-manager
    path: logs-in-console-format-cmd-arg-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: build-service-controller-manager
    path: image-expiration-patch.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: build-service-controller-manager
    path: pac-webhook-insecure-ssl-patch.yaml
components:
  - ../components/rh-certs
