apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: service-provider-integration-operator
    app.kubernetes.io/part-of: service-provider-integration-operator
    control-plane: controller-manager
    app.kubernetes.io/version: 0.2.0
  name: service-provider-integration-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: service-provider-integration-operator
      app.kubernetes.io/part-of: service-provider-integration-operator
      control-plane: controller-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-provider-integration-operator
        app.kubernetes.io/part-of: service-provider-integration-operator
        control-plane: controller-manager
    spec:
      containers:
        - args:
            - --leader-elect
          command:
            - /manager
          env:
            - name: SPI_URL
              value: http://service-provider-integration-api
          image: quay.io/redhat-appstudio/service-provider-integration-operator:next
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          name: manager
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 20Mi
          securityContext:
            allowPrivilegeEscalation: false
          volumeMounts:
            - mountPath: /tmp/k8s-webhook-server/serving-certs
              name: cert
              readOnly: true
            - mountPath: /etc/spi/config.yaml
              name: config
              subPath: config.yaml
            - mountPath: /etc/spi/shared-secret
              name: shared-secret
              subPath: shared-secret
      securityContext:
        runAsNonRoot: true
      serviceAccountName: spi-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-server-cert
        - configMap:
            name: spi-oauth-config-ht99mh7g66
          name: config
        - name: shared-secret
          secret:
            secretName: spi-shared-secret
