apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/part-of: service-provider-integration-operator
  name: spi-controller-manager
  namespace: spi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/part-of: service-provider-integration-operator
  name: spi-leader-election-role
  namespace: spi
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/part-of: service-provider-integration-operator
  name: spi-manager-role
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - spiaccesstokenbindings
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - spiaccesstokenbindings/finalizers
    verbs:
      - update
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - spiaccesstokenbindings/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - spiaccesstokens
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - spiaccesstokens/finalizers
    verbs:
      - update
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - spiaccesstokens/status
    verbs:
      - get
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/part-of: service-provider-integration-operator
  name: spi-metrics-reader
rules:
  - nonResourceURLs:
      - /metrics
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: service-provider-integration-oauth
    app.kubernetes.io/part-of: service-provider-integration-operator
  name: spi-oauth-clusterrole
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
      - get
  - apiGroups:
      - appstudio.redhat.com
    resources:
      - spiaccesstokens
    verbs:
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/part-of: service-provider-integration-operator
  name: spi-proxy-role
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/part-of: service-provider-integration-operator
  name: spi-leader-election-rolebinding
  namespace: spi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spi-leader-election-role
subjects:
  - kind: ServiceAccount
    name: spi-controller-manager
    namespace: spi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/part-of: service-provider-integration-operator
  name: spi-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spi-manager-role
subjects:
  - kind: ServiceAccount
    name: spi-controller-manager
    namespace: spi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: service-provider-integration-oauth
    app.kubernetes.io/part-of: service-provider-integration-operator
  name: spi-oauth-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spi-oauth-clusterrole
subjects:
  - kind: ServiceAccount
    name: spi-oauth-sa
    namespace: spi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/part-of: service-provider-integration-operator
  name: spi-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: spi-proxy-role
subjects:
  - kind: ServiceAccount
    name: spi-controller-manager
    namespace: spi
