## Or replace  with ExternalSecret
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/part-of: service-provider-integration-operator
  name: spi-serving-cert
  namespace: spi
spec:
  dnsNames:
    - spi-webhook-service.spi.svc
    - spi-webhook-service.spi.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: spi-selfsigned-issuer
  secretName: webhook-server-cert
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/part-of: service-provider-integration-operator
  name: spi-selfsigned-issuer
  namespace: spi
spec:
  selfSigned: {}