resources:
  - https://github.com/skabashnyuk/service-provider-integration-operator/config/default?ref=f6d79ce47bfce24eb072d4d4acc151bcfd95c3fc


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name:  quay.io/redhat-appstudio/service-provider-integration-operator
    newName: quay.io/redhat-appstudio/service-provider-integration-operator
    newTag: next
  - name: quay.io/redhat-appstudio/service-provider-integration-oauth
    newName: quay.io/redhat-appstudio/service-provider-integration-oauth
    newTag: next

namespace: spi-system