resources:
  - https://github.com/skabashnyuk/service-provider-integration-operator/config/default?ref=049b48752239174008ce1abf09173610a1488a09


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name:  quay.io/redhat-appstudio/service-provider-integration-operator
    newName: quay.io/redhat-appstudio/service-provider-integration-operator
    newTag: next
  - name: quay.io/redhat-appstudio/service-provider-integration-oauth
    newName: quay.io/redhat-appstudio/service-provider-integration-oauth
    newTag: next

namespace: spi-system