resources:
  - https://github.com/skabashnyuk/service-provider-integration-operator/config/default?ref=cc3b036bfe06e3ae9f4c4e63cd2f1c8f0779c7f0


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name:  quay.io/redhat-appstudio/service-provider-integration-operator
    newName: quay.io/redhat-appstudio/service-provider-integration-operator
    newTag: next
  - name: quay.io/redhat-appstudio/service-provider-integration-oauth
    newName: quay.io/redhat-appstudio/service-provider-integration-oauth
    newTag: next

namespace: spi-system