apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: has
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - kcp-name: dev
  template:
    spec:
      source:
        repoURL: https://github.com/skabashnyuk/infra-deployments.git
        targetRevision: preview-spi-improvements
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spi
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - kcp-name: dev
  template:
    spec:
      source:
        repoURL: https://github.com/skabashnyuk/infra-deployments.git
        targetRevision: preview-spi-improvements
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spi-vault
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - kcp-name: dev
  template:
    spec:
      source:
        repoURL: https://github.com/skabashnyuk/infra-deployments.git
        targetRevision: preview-spi-improvements
