apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - kcp-name: dev
  template:
    spec:
      source:
        repoURL: https://github.com/skabashnyuk/infra-deployments.git
        targetRevision: preview-SVPI-197-part2
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spi
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - kcp-name: dev
  template:
    spec:
      source:
        repoURL: https://github.com/skabashnyuk/infra-deployments.git
        targetRevision: preview-SVPI-197-part2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spi-vault
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/skabashnyuk/infra-deployments.git
    targetRevision: preview-SVPI-197-part2
